[project]
name = "pracy"
version = "0.0.1"
authors = [
  { name="Sven Argo", email="sven.argo@rub.de" }
]
readme = "README.md"
requires-python = ">=3.13"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
